Traceback (most recent call last):
  File "/Users/aaron/mambaforge/envs/bayes/lib/python3.10/site-packages/nbclient/client.py", line 626, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/Users/aaron/mambaforge/envs/bayes/lib/python3.10/site-packages/nbclient/util.py", line 96, in ensure_async
    result = await obj
  File "/Users/aaron/mambaforge/envs/bayes/lib/python3.10/site-packages/jupyter_client/asynchronous/channels.py", line 48, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron/mambaforge/envs/bayes/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/aaron/mambaforge/envs/bayes/lib/python3.10/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/aaron/mambaforge/envs/bayes/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/aaron/mambaforge/envs/bayes/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/aaron/mambaforge/envs/bayes/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Users/aaron/mambaforge/envs/bayes/lib/python3.10/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/Users/aaron/mambaforge/envs/bayes/lib/python3.10/site-packages/nbclient/client.py", line 838, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/Users/aaron/mambaforge/envs/bayes/lib/python3.10/site-packages/nbclient/client.py", line 650, in _async_poll_for_reply
    await self._async_handle_timeout(timeout, cell)
  File "/Users/aaron/mambaforge/envs/bayes/lib/python3.10/site-packages/nbclient/client.py", line 697, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
import pymc3 as pm
import arviz as az
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
az.style.use('arviz-darkgrid')
-------------------

